#!/bin/bash
PM=apt-get
if [ -f /etc/redhat-release ]; then
  PM=yum
fi
PHP=$(which php)
if [ $? == 1 ]; then
  sudo $PM install php-cli -y
fi
CURL=$(which curl)
if [ $? == 1 ]; then
  sudo $PM install curl -y
fi
WGET=$(which wget)
if [ $? == 1 ]; then
  sudo $PM install wget -y
fi
UNZIP=$(which unzip)
if [ $? == 1 ]; then
  sudo $PM install unzip -y
fi
COMPOSER=$(which composer)
if [ $? == 1 ]; then
  curl -sS https://getcomposer.org/installer | php
  sudo mv composer.phar /usr/local/bin/composer
fi
if test $1; then
  if [[ $1 == "up" || $1 == "update" ]]; then
    if [ -d $HOME/drush6 ]; then
      cd $HOME/drush6
      composer update
    else
      echo "drush6 directory does not exist."
    fi
    if [ -d $HOME/drush7 ]; then
      cd $HOME/drush7
      composer update
    else
      echo "drush7 directory does not exist."
    fi
    if [ -d $HOME/drush8 ]; then
      cd $HOME/drush8
      composer update
    else
      echo "drush8 directory does not exist."
    fi
    if [ -d $HOME/.composer ]; then
      composer global update drush/drush
    fi
    if [ -d $HOME/.config/composer ]; then
      composer global update drush/drush
    fi
  else
    echo "Usage: $0 [up|update]"
  fi
  exit 0
fi
cd
if [ ! -d drush5 ]; then
  wget https://github.com/drush-ops/drush/archive/5.10.0.zip
  unzip 5.10.0.zip
  mv drush-5.10.0 drush5
  rm -f 5.10.0.zip
fi
if [ ! -d drush6 ]; then
  mkdir drush6
  cd drush6
  composer require drush/drush:6.*
  cd
fi
if [ ! -d drush7 ]; then
  mkdir drush7
  cd drush7
  composer require drush/drush:7.*
  cd
fi
if [ ! -d drush8 ]; then
  mkdir drush8
  cd drush8
  composer require drush/drush:8.*
  cd
fi
composer global require consolidation/robo:dev-master
composer global require symfony/console:2.7.*
composer global require symfony/event-dispatcher:2.7.*
composer global require drush/drush:dev-master
DRUSH5=$(grep 'alias drush5=' .bash_aliases 2> /dev/null)
if [ -z $DRUSH5 ]; then
cat << "EOF" >> .bash_aliases
alias drush5=$HOME/drush5/drush
EOF
fi
DRUSH6=$(grep 'alias drush6=' .bash_aliases)
if [ -z $DRUSH6 ]; then
cat << "EOF" >> .bash_aliases
alias drush6=$HOME/drush6/vendor/bin/drush
EOF
fi
DRUSH7=$(grep 'alias drush7=' .bash_aliases)
if [ -z $DRUSH7 ]; then
cat << "EOF" >> .bash_aliases
alias drush7=$HOME/drush7/vendor/bin/drush
EOF
fi
DRUSH8=$(grep 'alias drush8=' .bash_aliases)
if [ -z $DRUSH8 ]; then
cat << "EOF" >> .bash_aliases
alias drush8=$HOME/drush8/vendor/bin/drush
EOF
fi
echo "export PATH=\"$HOME/.config/composer/vendor/bin:$HOME/.composer/vendor/bin:$PATH\"" >> .bashrc
source .bashrc
$HOME/drush5/drush --version
$HOME/drush6/vendor/bin/drush --version
$HOME/drush7/vendor/bin/drush --version
$HOME/drush8/vendor/bin/drush --version
drush --version
