#!/bin/bash
PM=apt-get
if [ -f /etc/redhat-release ]; then
  PM=yum
fi
PHP=$(command -v php)
if [ $? == 1 ]; then
  sudo $PM install php-cli -y
fi
CURL=$(command -v curl)
if [ $? == 1 ]; then
  sudo $PM install curl -y
fi
WGET=$(command -v wget)
if [ $? == 1 ]; then
  sudo $PM install wget -y
fi
UNZIP=$(command -v unzip)
if [ $? == 1 ]; then
  sudo $PM install unzip -y
fi
COMPOSER=$(command -v composer)
if [ $? == 1 ]; then
  curl -sS https://getcomposer.org/installer | php
  sudo mv composer.phar /usr/local/bin/composer
fi
DEFAULT=9
VALID_VERSIONS="4 5 6 7 8 9"
if test $1; then
  VALID=
  VALID_COMMANDS="up update -d --default"
  for C in $VALID_COMMANDS; do
    if [ $C == $1 ]; then
      VALID=1
    fi
  done
  if [ -z $VALID ]; then
    echo "Usage: $0 [up|update|-d #|--default #]"
    echo "       Valid default values are $VALID_VERSIONS."
    exit 1
  fi
  if [[ $1 == "-d" || $1 == "--default" ]]; then
    DEFAULT=
    for V in $VALID_VERSIONS; do
      if [ $V == $2 ]; then
        DEFAULT=$2
      fi
    done
    if [ -z $DEFAULT ]; then
      echo "Invalid default version.  Valid values are $VALID_VERSIONS."
      exit 1
    fi
    cd
    sudo ln -fs /usr/local/bin/drush$DEFAULT /usr/local/bin/drush
    echo "Default:"
    drush --version
  fi
  if [[ $1 == "up" || $1 == "update" ]]; then
    if [ -d $HOME/drush6 ]; then
      cd $HOME/drush6
      composer update
    else
      echo "drush6 directory does not exist."
    fi
    if [ -d $HOME/drush7 ]; then
      cd $HOME/drush7
      composer update
    else
      echo "drush7 directory does not exist."
    fi
    if [ -d $HOME/drush8 ]; then
      cd $HOME/drush8
      composer update
    else
      echo "drush8 directory does not exist."
    fi
    if [ -d $HOME/drush9 ]; then
      cd $HOME/drush9
      composer update
    else
      echo "drush9 directory does not exist."
    fi
  fi
  exit 0
fi
cd
if [ ! -d drush4 ]; then
  wget https://github.com/drush-ops/drush/archive/4.6.0.zip
  unzip 4.6.0.zip
  mkdir -p drush4/vendor
  mv drush-4.6.0 drush4/vendor/bin
  rm -f 4.6.0.zip
fi
if [ ! -d drush5 ]; then
  wget https://github.com/drush-ops/drush/archive/5.10.0.zip
  unzip 5.10.0.zip
  mkdir -p drush5/vendor
  mv drush-5.10.0 drush5/vendor/bin
  rm -f 5.10.0.zip
fi
if [ ! -d drush6 ]; then
  mkdir drush6
  cd drush6
  composer require drush/drush:6.*
  cd
fi
if [ ! -d drush7 ]; then
  mkdir drush7
  cd drush7
  composer require drush/drush:7.*
  cd
fi
if [ ! -d drush8 ]; then
  mkdir drush8
  cd drush8
  composer require drush/drush:8.*
  cd
fi
if [ ! -d drush9 ]; then
  mkdir drush9
  cd drush9
  composer config minimum-stability beta
  composer require drush/drush:9.*
  cd
fi
if [ ! -h /usr/local/bin/drush4 ]; then
  sudo ln -s $HOME/drush4/vendor/bin/drush /usr/local/bin/drush4
fi
if [ ! -h /usr/local/bin/drush5 ]; then
  sudo ln -s $HOME/drush5/vendor/bin/drush /usr/local/bin/drush5
fi
if [ ! -h /usr/local/bin/drush6 ]; then
  sudo ln -s $HOME/drush6/vendor/bin/drush /usr/local/bin/drush6
fi
if [ ! -h /usr/local/bin/drush7 ]; then
  sudo ln -s $HOME/drush7/vendor/bin/drush /usr/local/bin/drush7
fi
if [ ! -h /usr/local/bin/drush8 ]; then
  sudo ln -s $HOME/drush8/vendor/bin/drush /usr/local/bin/drush8
fi
if [ ! -h /usr/local/bin/drush9 ]; then
  sudo ln -s $HOME/drush9/vendor/bin/drush /usr/local/bin/drush9
fi
sudo ln -fs $HOME/drush$DEFAULT/vendor/bin/drush /usr/local/bin/drush
drush4 --version
drush5 --version
drush6 --version
drush7 --version
drush8 --version
drush9 --version
echo "Default:"
drush --version
